### ISSUE TITLE
error message typo; references ~/.nrbc file

### ISSUE THREAD

**Issue by richardsc** [dankelley/nota#10]
Note that this bug report is for the pypi version of nota -- I haven't checked the devel version, because the error message only arises due to the fact my installed pypi version doesn't yet know about the color themes (I have `bubblegum` set in my ~/.notarc file):

```
$ nota
Unknown color scheme color="bubblegum" specified in ~/.nrbc file.
```

Note that error references `~/.nrbc`, which should be `~/.notarc`.

**Comment by dankelley** [comment]
I think the devel and master branches are clean, according to
```
git grep nbrc
```

**Comment by richardsc** [comment]
Ah, that's a good command to know. Closing.
