### ISSUE TITLE
note content echo after `nota -a`

### ISSUE THREAD

**Issue by richardsc** [dankelley/nota#13]
For some reason now when I use `nota -a` to add a note, when finished it spits out the db contents to the command line. E.g.:

```
$ n -a   ## opens an editor for filling out fields -- when done save and quit, and then:
ee: {'privacy': 0, 'title': 'test', 'due': '', 'content': '\nA test.', 'book': 1, 'keywords': ['test']}
```

**Comment by dankelley** [comment]
Can you re-pull and re-build? I think this one was fixed this morning.

PS. build instructions are in ``README-developer.rst``

**Comment by richardsc** [comment]
Yes, this seems ok now. I also realized that I was still on the `testing` branch, which was behind develop.

**Comment by dankelley** [comment]
Yes, I get myself quite confused on the branches. PS. I uploaded to pypi today, as per my schedule. I also updated oce's master branch.
