### ISSUE TITLE
Should trashed notes be returned in searches?

### ISSUE THREAD

**Issue by richardsc** [dankelley/nota#7]
Currently a note search done either by not typing a complete hash, or by keyword, will return notes that are in the trash. I'm not sure if this is desired or not.

I would make the argument that trashed notes shouldn't be seen, unless one specifically *asks* to see them (e.g. `nota --trash`).

Another option could be to tie verbosity into the search results, e.g. to make notes that match the search terms but that are in the trash be labelled as such. Maybe something like:
```
$ nota -k foo
a1: Note 1 [foo, bar, foobar]
b2: Note 2 [foo, oof]
2 Trashed notes match search (c3, d4)
```
but with `--verbosity 0` you would see
```
$ nota -k foo
a1: Note 1 [foo, bar, foobar]
b2: Note 2 [foo, oof]
```

**Comment by dankelley** [comment]
There is also the question of hash matches, which should behave similarly.  The simplest form
```
nota
```
is actually a hash search that matches all non-trashed hashes, and reports just a number for the trash size. Maybe keyword searches should be the same. I don't quite prefer to see the hashes listed as in your first code block (what if there are 300 there?), and a normal call doesn't do that. I think, for consistency with hash searches, it should be necessary to give ``--trash``. Thus,
```
nota # gives notes, plus number of trash notes (if verbosity>0)
nota --trash # gives just notes in trash
nota -k X # gives notes, plus number of trash notes (if verbosity>0)
nota -k X --trash # gives just notes in the trash with given keyword
```

**Comment by dankelley** [comment]
@richardsc what do you think of the 5-bullet plan in the comment immediately above? Somehow I get too close to things to see the best scheme. My plan on this will be to (a) decide on the functionality, (b) write docs for that functionality (that say "BROKEN" all over the place) and only then to (c) write the code. If I skip to writing code too early,  there is a danger of having a mixed-up scheme. (Plus the coding takes 3 times as long.)

**Comment by richardsc** [comment]
I like the 5-bullet syntax you've proposed.

**Comment by dankelley** [comment]
I think this is working ok now in ``master`` and ``develop``, but I plan to use it for a couple of days to see if any new problems have arisen, because the code modifications were significant.

**Comment by richardsc** [comment]
I've found some undesired behaviour. I've created an alternate database for testing, and aliased it to `nt`, which explains the different command I'm using.

Basically, when I do a keyword search, the trash listing is given wrong results. I'll walk through it.

First, just list the db:
```
$ nt
b: Walter Lewin physics lectures [lecture, physics, MIT]
3: foo [foo]
4: bar [bar]
d: foo bar [foo, bar]
The trash has no notes matching this search.
Hint: add a note: 'nota -a' (opens EDITOR)
```
Note that there are no trashed notes. Now, search for keyword `foo`:
```
$ nt -k foo
3: foo [foo]
d: foo bar [foo, bar]
The trash has 2 notes matching this search.
Hint: create new note hashes: 'nota --developer=rehash'
```
This now says that there are 2 trashed notes, even though there are no notes in the trash. Now do the keyword search in the trash:
```
$ nt -k foo --trash
3: foo [foo]
d: foo bar [foo, bar]
```
and it returns the two *non-trashed* notes.

**Comment by dankelley** [comment]
Any chance you could email me your ``.db`` file? That would make debugging easier.  From what I am reading above it looks like my newly-added code has a flag reversed.

If you don't want to email, you could try 
```
nota --export - | pbcopy
```
and then email that or paste the output here. (This lets us test whether ``--import`` and ``--export`` are working cleanly.)

**Comment by dankelley** [comment]
I realized that your db was very simple, constructed by e.g.
```
mv ~/Dropbox/nota.db ~/Dropbox/nota.db
nota -a -t "Walter Lewin physics lectures" -k lecture, physics,MIT
nota -a -t foo -k foo
nota -a -t bar -k bar
nota -a "foo bar" -k foo,bar
```
so I went ahead and did some tests. I think it works ok now (in ``master`` and ``develop``).

Seem ok to you?

**Comment by richardsc** [comment]
Yup, seems like it works now. And yes, I decided to make a simple test db so that I'm not messing around with my **real** notes (because I'm actually using it quite a bit these days!)
