### ISSUE TITLE
cannot add notes containing some symbols

### ISSUE THREAD

**Issue by dankelley** [dankelley/nota#9]
I tried to add a note that had French text, and it croaked. It also croaked on angled quote marks (from R output)
```
* preparing ‘oce’:
```

Thus, I think it's basically going to croak on lots of "complex" text.

**Comment by dankelley** [comment]
Test code
```
n -a -t 'test' -c "preparing ‘oce’" --debug
```

**Comment by richardsc** [comment]
This must be an encoding issue? I thought it was using UTF-8 or something, which should be fine with most "fancy" characters.

**Comment by dankelley** [comment]
I think the encoding was something that got removed in that patch in issue #3. I'm looking into this. Should not be hard to find; a search is revealing a lot of people doing such-like.

**Comment by dankelley** [comment]
Fixed on github but not yet released to pypi; I'll leave the bug open until I've uploaded to pypi.

(I want to address #7 and #8 before uploading to pypi.)
